# Generated by Django 3.2 on 2021-04-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0005_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elearn.user')),
                ('interests', models.ManyToManyField(related_name='interested_learners', to='elearn.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='elearn.learner')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='elearn.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='quizzes',
            field=models.ManyToManyField(through='elearn.TakenQuiz', to='elearn.Quiz'),
        ),
    ]
