# Generated by Django 3.2 on 2021-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0007_learneranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
