# Generated by Django 3.2 on 2021-05-01 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0009_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='elearn.course'),
        ),
    ]
