# Generated by Django 3.2 on 2021-05-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0011_tutorial_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='author',
            new_name='user',
        ),
    ]
