# Generated by Django 3.2 on 2021-05-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0013_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='elearn.user')),
                ('interest', models.ManyToManyField(related_name='interested_instructor', to='elearn.Course')),
            ],
        ),
    ]
