# Generated by Django 3.2 on 2021-05-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0014_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-2000, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='interest',
            field=models.ManyToManyField(related_name='more_locations', to='elearn.Course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
